### ISSUE TITLE
Minimum brand planing & content

### ISSUE THREAD

**Issue by dride-for-sure** [dride-for-sure/schulatlas#3]
**Minimum brand planing & content**

- [x] Finalize color scheme and check vs WCAG 2.0
- [x] Brainstorm hero headlines
- [x] Rethink CTAs & their colors
- [x] Rethink Nav Items 
- [x] Select and buy images (Minimum 2k in resolution)
